repository: kaltokri/just-the-docs-test
title: DCSServerBot
description: A Python tool tp connect DCS server with Discord!
theme: just-the-docs
color_scheme: dark

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: https://github.com/kaltokri/just-the-docs-test
gh_edit_branch: main
gh_edit_source: docs
gh_edit_view_mode: edit

aux_links:
  GitHub: https://github.com/Special-K-s-Flightsim-Bots/DCSServerBot
  Discord: https://discord.gg/zjRateN
  Patreon: https://www.patreon.com/DCS_SpecialK
