repository: kaltokri/just-the-docs-test
title: Just the Docs Test
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs
color_scheme: dark

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: https://github.com/kaltokri/just-the-docs-test
gh_edit_branch: main
gh_edit_source: docs
gh_edit_view_mode: edit

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
